name: Continous Deploy

on:
  push:
    branches:
      - master
      - Sprint2
      - Sprint3
      - Sprint4
      - Sprint5
      - Sprint6
      - Sprint7
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: Install SSH key
        run: echo $SSH_KEY | base64 --decode  > ./id_rsa
        env:
          SSH_KEY: ${{ secrets.DEPLOY_ACCOUNT_CERTIFICATE }}

      - name: Pull commits into running dev
        uses: appleboy/ssh-action@master
        env:
            GITHUB_BRANCH: ${{ github.ref }}
        with:
          host: dev.fossilfuelregistry.org
          username: grff
          key_path: ./id_rsa
          envs: GIT_BRANCH
          script: |
            pwd
            id
            cd grff-portal
            git checkout master
            git fetch --all
            git reset --hard origin/master
            yarn build
            pm2 restart 0
