name: Continous Deploy

on:
  push:
    branches:
      - master
      - Sprint2

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@Sprint2

      - name: Install SSH key
        run: echo $SSH_KEY | base64 --decode  > ./id_rsa
        env:
          SSH_KEY: ${{ secrets.DEPLOY_ACCOUNT_CERTIFICATE }}

      - name: Pull commits into running dev
        uses: appleboy/ssh-action@master
        with:
          host: dev.fossilfuelregistry.org
          username: grff
          key_path: ./id_rsa
          script: |
            pwd
            id
            cd grff-portal
            git pull
